import { mkdirSync, readFileSync, writeFileSync, renameSync } from 'node:fs';
import { join } from 'node:path';
const key=process.env.YOUTUBE_API_KEY;
const ids='2MYden2yjVU,LJop4DC_aKI,jLLpxYesqTA,WgCZDoJIckw,rnmiNf_NOVc,KqCQUTDkRcs,Ih6aBi43Fho,PL9zZRWRMI4'.split(',');
if(!key){console.error('Missing YOUTUBE_API_KEY. Set it for maintainer-only seed bootstrap; no key is written.');process.exit(1)}
const u=new URL('https://www.googleapis.com/youtube/v3/videos');u.searchParams.set('part','snippet,contentDetails,status,liveStreamingDetails');u.searchParams.set('id',ids.join(','));u.searchParams.set('key',key);
const response=await fetch(u);if(!response.ok){console.error(`YouTube API ${response.status}`);process.exit(1)}
const data:any=await response.json();const by=new Map((data.items??[]).map((v:any)=>[v.id,v]));const rows=ids.map(id=>{const v=by.get(id);return v?{videoId:v.id,channelId:v.snippet?.channelId??null,channelTitle:v.snippet?.channelTitle??null,title:v.snippet?.title??null,duration:v.contentDetails?.duration??null,privacyStatus:v.status?.privacyStatus??null,embeddable:v.status?.embeddable??null,liveBroadcastContent:v.snippet?.liveBroadcastContent??null,publishedAt:v.snippet?.publishedAt??null}: {videoId:id,missing:true}});
const channels=[...new Map(rows.filter((r:any)=>r.channelId).map((r:any)=>[r.channelId,{channelId:r.channelId,channelTitle:r.channelTitle,discoveredFromVideoIds:rows.filter((x:any)=>x.channelId===r.channelId).map((x:any)=>x.videoId)}])).values()];
mkdirSync(join(process.cwd(),'artifacts/youtube-catalog'),{recursive:true});mkdirSync(join(process.cwd(),'config'),{recursive:true});const atomic=(p:string,v:any)=>{const t=p+'.tmp';writeFileSync(t,JSON.stringify(v,null,2)+'\n');JSON.parse(readFileSync(t,'utf8'));renameSync(t,p)};atomic(join(process.cwd(),'artifacts/youtube-catalog/seed-channels.json'),{generatedAt:new Date().toISOString(),videoCount:ids.length,foundCount:data.items?.length??0,videos:rows,channels});atomic(join(process.cwd(),'config/youtube-sources.candidates.json'),{schemaVersion:1,generatedAt:new Date().toISOString(),sources:channels.map((c:any)=>({channelId:c.channelId,category:'other',weight:1,enabled:false,maxVideos:30,discoveredFromVideoIds:c.discoveredFromVideoIds}))});console.log(`seed metadata saved; unique channels: ${channels.length}`);
