import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

type Category = 'humor'|'gaming'|'animals'|'technology'|'music_art'|'other';
const root=process.cwd(), outDir=join(root,'artifacts/youtube-catalog'), apiBase='https://www.googleapis.com/youtube/v3';
const key=process.env.YOUTUBE_API_KEY;
function atomic(path:string,value:unknown){const tmp=path+'.tmp';writeFileSync(tmp,JSON.stringify(value,null,2)+'\n');JSON.parse(readFileSync(tmp,'utf8'));renameSync(tmp,path)}
async function request(path:string,params:Record<string,string>){if(!key)throw Error('Missing YOUTUBE_API_KEY (maintainer-only).');const u=new URL(`${apiBase}/${path}`);for(const [k,v] of Object.entries({...params,key}))u.searchParams.set(k,v);const r=await fetch(u);if(!r.ok)throw Error(`YouTube API ${r.status} (${path})`);return r.json() as Promise<any>}
function seconds(value:string|undefined){const m=/^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/.exec(value||'');return m?Number(m[1]||0)*3600+Number(m[2]||0)*60+Number(m[3]||0):0}
async function resolve(){if(!key)throw Error('Missing YOUTUBE_API_KEY (maintainer-only). No files written.');const cfg=JSON.parse(readFileSync(join(root,'config/youtube-channel-handles.json'),'utf8'));const results:any[]=[];for(const c of cfg.channels){try{const x=await request('channels',{part:'id,snippet,contentDetails,status',forHandle:c.handle});const item=x.items?.[0];const id=item?.id;results.push({handle:c.handle,channelId:id||'',channelTitle:item?.snippet?.title||'',uploadsPlaylistId:item?.contentDetails?.relatedPlaylists?.uploads||'',category:c.category,weight:c.weight,resolutionStatus:id&&/^UC[\w-]{20,}$/.test(id)?'resolved':x.items?.length?'ambiguous':'not-found'});}catch(error){results.push({handle:c.handle,channelId:'',channelTitle:'',uploadsPlaylistId:'',category:c.category,weight:c.weight,resolutionStatus:'error',error:String(error)})}}mkdirSync(outDir,{recursive:true});atomic(join(outDir,'resolved-channels.json'),{generatedAt:new Date().toISOString(),channels:results});console.log(`resolved ${results.filter(x=>x.resolutionStatus==='resolved').length}/${results.length} handles`)}
async function collect(){if(!key)throw Error('Missing YOUTUBE_API_KEY (maintainer-only). No files written.');const resolved=JSON.parse(readFileSync(join(outDir,'resolved-channels.json'),'utf8')).channels.filter((x:any)=>x.resolutionStatus==='resolved');const block=JSON.parse(readFileSync(join(root,'config/youtube-video-blocklist.json'),'utf8'));const blocked=new Set(block.videoIds||[]);const scan=Math.min(200,Math.max(1,Number(process.env.SCAN_UPLOADS||50)));const channels:any[]=[];for(const c of resolved){try{
// The uploads playlist mixes long-form with shorts, and there is no shorts-only
// playlist in the Data API. A ten-item window therefore reports zero eligible
// videos for any channel whose recent uploads happen to be long-form.
const items:any[]=[];let token='';do{const page=await request('playlistItems',{part:'snippet,contentDetails',playlistId:c.uploadsPlaylistId,maxResults:'50',...(token?{pageToken:token}:{})});items.push(...(page.items||[]));token=page.nextPageToken||''}while(token&&items.length<scan);const ids=items.slice(0,scan).map((x:any)=>x.contentDetails?.videoId).filter(Boolean);const response={items:[] as any[]};for(let i=0;i<ids.length;i+=50)response.items.push(...((await request('videos',{part:'snippet,contentDetails,status',id:ids.slice(i,i+50).join(',')})).items||[]));const eligible:any[]=[],rejected:any[]=[];for(const v of response.items||[]){const d=seconds(v.contentDetails?.duration), reasons:string[]=[];if(!v.id)reasons.push('missing');else if(blocked.has(v.id))reasons.push('blocked');if(v.status?.privacyStatus!=='public')reasons.push('private');if(v.status?.embeddable!==true)reasons.push('unembeddable');if(v.snippet?.liveBroadcastContent!=='none')reasons.push('live');if(d<3||d>180)reasons.push(d>180?'too-long':'invalid-duration');const item={videoId:v.id,channelId:c.channelId,channelTitle:v.snippet?.channelTitle,title:v.snippet?.title,duration:v.contentDetails?.duration,publishedAt:v.snippet?.publishedAt,category:c.category,weight:c.weight};(reasons.length?rejected:eligible).push(reasons.length?{...item,rejectionReasons:reasons}:item)}channels.push({...c,publicationCount:response.items?.length||0,eligible,rejected})}catch(error){channels.push({...c,publicationCount:0,eligible:[],rejected:[],error:String(error)})}}mkdirSync(outDir,{recursive:true});atomic(join(outDir,'permanent-candidates.json'),{generatedAt:new Date().toISOString(),channels});atomic(join(outDir,'permanent-candidates-summary.json'),{generatedAt:new Date().toISOString(),channels:channels.map(c=>({channelId:c.channelId,channelTitle:c.channelTitle,handle:c.handle,eligible:c.eligible.length,rejected:c.rejected.length}))});console.log(`checked ${channels.length} resolved channels`)}
function autoApprove(){const candPath=join(outDir,'permanent-candidates.json');if(!existsSync(candPath))throw Error('Missing artifacts/youtube-catalog/permanent-candidates.json - run resolve/collect first');const threshold=Number(process.env.MIN_ELIGIBLE||3);if(!Number.isFinite(threshold)||threshold<1)throw Error('MIN_ELIGIBLE must be a positive integer');const candidates=JSON.parse(readFileSync(candPath,'utf8')).channels||[];const current=JSON.parse(readFileSync(join(root,'config/youtube-sources.json'),'utf8'));const byId=new Map<string,any>();
// Carry the live allowlist through untouched: `apply` replaces `sources` wholesale,
// so a review file naming only the new channels would silently drop every old one.
for(const s of current.sources||[])byId.set(s.channelId,{channelId:s.channelId,channelTitle:'',handle:'',category:s.category,weight:s.weight,decision:s.enabled?'approve-channel':'reject-channel',eligible:null,rejected:null,origin:'allowlist'});
for(const c of candidates){if(!/^UC[\w-]{20,}$/.test(c.channelId||''))continue;const eligible=(c.eligible||[]).length,rejected=(c.rejected||[]).length;const prior=byId.get(c.channelId);const decision=eligible>=threshold?'approve-channel':prior?.decision==='approve-channel'?'approve-channel':'reject-channel';byId.set(c.channelId,{channelId:c.channelId,channelTitle:c.channelTitle||'',handle:c.handle||'',category:c.category||prior?.category||'other',weight:Number(c.weight||prior?.weight||1),decision,eligible,rejected,origin:prior?'allowlist':'candidate'})}
const channels=[...byId.values()];const approved=channels.filter(c=>c.decision==='approve-channel');if(!approved.length)throw Error('No channel reached the threshold; review file not written');mkdirSync(outDir,{recursive:true});atomic(join(outDir,'permanent-channel-review.json'),{generatedAt:new Date().toISOString(),minEligible:threshold,channels});
for(const c of channels.filter(x=>x.origin==='candidate'))console.log(`${c.decision==='approve-channel'?'approve':'reject '} ${c.eligible}/${c.eligible+c.rejected} eligible  ${String(c.category).padEnd(10)} ${c.handle||c.channelId} ${c.channelTitle}`);
console.log(`threshold >=${threshold} eligible; approved ${approved.length}/${channels.length} (allowlist ${(current.sources||[]).length} -> ${approved.length}). Review artifacts/youtube-catalog/permanent-channel-review.json, then run apply-review.`)}
function apply(){const reviewPath=join(outDir,'permanent-channel-review.json');if(!existsSync(reviewPath))throw Error('Missing artifacts/youtube-catalog/permanent-channel-review.json');const review=JSON.parse(readFileSync(reviewPath,'utf8'));const decisions=review.channels||review;const sources=decisions.filter((x:any)=>x.decision==='approve-channel').map((x:any)=>({channelId:x.channelId,category:x.category||'other',weight:Number(x.weight||1),enabled:true,maxVideos:Number(process.env.MAX_VIDEOS||50)}));if(!sources.length)throw Error('Review contains no approved channels; allowlist unchanged');const current=join(root,'config/youtube-sources.json');const old=JSON.parse(readFileSync(current,'utf8'));mkdirSync(outDir,{recursive:true});atomic(join(outDir,'youtube-sources.backup.json'),old);console.log(`allowlist diff: ${old.sources.length} -> ${sources.length}`);atomic(current,{schemaVersion:1,maxVideoAgeDays:old.maxVideoAgeDays||30,catalogLimit:old.catalogLimit||200,sources})}
async function main(){const mode=process.argv[2];if(mode==='resolve'){await resolve();return}if(mode==='collect'){await collect();return}if(mode==='auto-approve'){autoApprove();return}if(mode==='apply'){apply();return}throw new Error('Usage: catalog-youtube-permanent.ts resolve|collect|auto-approve|apply')}
main().catch((error)=>{console.error(error instanceof Error?error.message:String(error));process.exitCode=1});
